packages:
  - 'apollo'
  - 'ares'
  - 'art'
  - 'artemis'
  - 'athena'
  - 'codegen'
  - 'deimos'
  - 'dionysus'
  - 'docs'
  - 'eslint-plugin'
  - 'fixtures'
  - 'hera'
  - 'hermes'
  - 'i18n'
  - 'offline'
  - 'scripts'
  - 'tests'
  - 'ui'
  - 'zeus'
